apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
spec:
  volumes:
  - name: www
  - name: test
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html/
    - name: test
      mountPath: /home/
  - name: git
    image: alpine
    command: [ "sh", "-c", "apk add --no-cache git && git clone https://github.com/octocat/Spoon-Knife /www && echo 'prueba' > /da_igual/test.txt" ]
    volumeMounts:
    - name: www
      mountPath: /www/
    - name: test
      mountPath: /da_igual/
  restartPolicy: OnFailure

